### Login: Send POST request with json body
POST http://localhost:8080/login
Content-Type: application/json

{
  "tel": "12345678",
  "password": "12345678"
}

### response (status, value)
### status: false    value: 'invalid user'
### status: false    value: 'wrong password'
### status: false    value: 'no records'
### status: true     value: jobs （以数组的形式返回，数组元素为 object 对象）
#[ { item_id: 1, name: '拍摄电表读数' },
#  { item_id: 2, name: '拍摄电表输入' },
#  { item_id: 3, name: '拍摄电表输出' },
#  { item_id: 4, name: '拍摄防雷' },
#  { item_id: 5, name: '拍摄空调' } ]


### upload task and shot: send post with multipart/form-data
POST http://localhost:8080/task/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=------------WebAppBoundary23333
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTIzNDU2NzgiLCJyb2xlIjoidXNlciIsImlhdCI6MTU0Mjk0MjUwMCwiZXhwIjoxNTQyOTQzOTQwfQ.GApCjm7dfc30fZrva8QOobm4ZQXr7bsjB01TITe5LUg

--------------WebAppBoundary23333
Content-Disposition: form-data; name="fields"
Content-Type: application/json

{
  "tasks": {
    "taskItemId": {
      "abnormal": 1,
      "output": "前后拍摄图片差异较大，建议人手查看",
      "shot": {
        "completedTime": "2018/12/12",
        "output": "ocr value"
      }
    }
  },
  "jobId": 2
}

--------------WebAppBoundary23333
Content-Disposition: form-data; name="png1"; filename="2333_2.png"
Content-Type: image/png

< ./public/img/2333.png

--------------WebAppBoundary23333
Content-Disposition: form-data; name="png2"; filename="aaa_2.png"
Content-Type: image/png

< ./public/img/aaa.png
--------------WebAppBoundary23333


###demo
### Send a form with the text and file fields
POST https://httpbin.org/post
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="element-name"
Content-Type: text/plain

Name
--WebAppBoundary
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ./request-form-data.json
--WebAppBoundary--

###

POST http://localhost:8080/