### admin login
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
  "tel": "22345678",
  "password": "22345678"
}

### create users: send post with json body
POST http://localhost:8080/user/create HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMjIzNDU2NzgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDI5NjUwMTgsImV4cCI6MTU0Mjk2NjQ1OH0.7iVOpNK1v7J_BksbQEvWfvaqOSldVZHCBZM2FQnOcxo

{
  "tel": "13422214258",
  "disabled": 0,
  "name": "Lucy",
  "sex": "f",
  "age": 34,
  "role": null
}

### get all users' message: send get
GET http://localhost:8080/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMjIzNDU2NzgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDI5NjUwMTgsImV4cCI6MTU0Mjk2NjQ1OH0.7iVOpNK1v7J_BksbQEvWfvaqOSldVZHCBZM2FQnOcxo


### create tower: send post with json body
POST http://localhost:8080/tower/create HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMjIzNDU2NzgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDI5NjUwMTgsImV4cCI6MTU0Mjk2NjQ1OH0.7iVOpNK1v7J_BksbQEvWfvaqOSldVZHCBZM2FQnOcxo

{
  "code": "towerA_1",
  "name": "towerA",
  "address": "Guangzhou Guangdong",
  "lat": 46.50,
  "lng": 20.0,
  "type": "base type"
}

### create task items
POST http://localhost:8080/task-item/create HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMjIzNDU2NzgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDI5NjUwMTgsImV4cCI6MTU0Mjk2NjQ1OH0.7iVOpNK1v7J_BksbQEvWfvaqOSldVZHCBZM2FQnOcxo

{
  "namesArr": ["拍摄电表读数", "拍摄电表输入"]
}

### get all task item
GET http://localhost:8080/task-item HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMjIzNDU2NzgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDI5NjU1MjAsImV4cCI6MTU0Mjk2Njk2MH0.5MR9emBr0SXsNiw2_3feEU2o-RBTHUEwKHB0zRQpA5E

### upload excel file about job massage
POST http://localhost:8080/job/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=------------WebAppBoundary201811
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMjIzNDU2NzgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1NDMxMTMwODIsImV4cCI6MTU0MzExNDUyMn0.tDS9h5BmhSKXnuN69ePgz7fwJMRMfq0SVjKtOnWfRqU

--------------WebAppBoundary201811
Content-Disposition: form-data; name="jobFile"; filename="巡检任务表.xlsx"
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary

< C:\Users\54423\Desktop\巡检任务表.xlsx
--------------WebAppBoundary201811

###
